apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  liveness:
    path: /internal/alive
    initialDelay: 20
  readiness:
    path: /internal/ready
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  ingresses:
    - https://www.nav.no/arbeid/start-samtale
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navnob2c.b2clogin.com
  gcp:
    buckets:
      - name: start-samtale-prod
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "start-samtale-prod"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "contextPath": "/arbeid/start-samtale",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "https://veilarbvedtakinfo.prod-fss-pub.nais.io/veilarbvedtakinfo", "toApp": { "name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarboppfolging", "toUrl": "https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging", "toApp": { "name": "veilarboppfolging", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "https://veilarbdialog.prod-fss-pub.nais.io/veilarbdialog", "toApp": { "name": "veilarbdialog", "namespace": "pto", "cluster": "prod-fss" } }
          ],
          "redirects": [
            {
              "fromPath": "/minside",
              "toUrl": "https://www.nav.no/minside",
              "preserveFromPath": "false"
            },
            {
              "fromPath": "/arbeidsrettet-dialog/*",
              "toUrl": "https://www.nav.no/arbeid/dialog",
              "preserveFromPath": "false"
            }
          ]
        }
