apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  liveness:
    path: /internal/alive
    initialDelay: 20
  readiness:
    path: /internal/ready
    initialDelay: 20
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  ingresses:
    - https://pto.dev.nav.no/arbeid/start-samtale
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navtestb2c.b2clogin.com
  gcp:
    buckets:
      - name: start-samtale-dev
  envFrom:
    - configmap: pto-config
    - configmap: loginservice-idporten
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "start-samtale-dev"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "contextPath": "/arbeid/start-samtale",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "http://pto-proxy/proxy/veilarbvedtakinfo" },
            { "fromPath": "/veilarboppfolging", "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io", "toApp": { "name": "veilarboppfolging", "namespace": "pto", "cluster": "dev-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io", "toApp": { "name": "veilarbdialog", "namespace": "pto", "cluster": "dev-fss" } }
          ],
          "redirects": [
            {
              "fromPath": "/minside",
              "toUrl": "{{MINSIDE_URL}}"
            },
            {
              "fromPath": "/arbeidsrettet-dialog",
              "toUrl": "{{ARBEIDSRETTET_DIALOG_URL}}",
              "preserveFromPath": "true"
            }
          ]
        }
