apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/pto-frontend/pto-frontend:2022.01.31_12.28-883b24c9ea53
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  ingresses:
    - https://www.nav.no/arbeid/test/start-samtale
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  accessPolicy:
    outbound:
      rules:
        - application: pto-proxy
      external:
        - host: navnob2c.b2clogin.com
  gcp:
    buckets:
      - name: start-samtale-prod
  envFrom:
    - configmap: pto-config
  env:
    - name: ENFORCE_LOGIN
      value: "true"
    - name: LOGIN_REDIRECT_URL
      value: https://loginservice.nav.no/login?redirect={RETURN_TO_URL}&level=Level4
    - name: OIDC_DISCOVERY_URL
      value: https://navnob2c.b2clogin.com/navnob2c.onmicrosoft.com/v2.0/.well-known/openid-configuration?p=B2C_1A_idporten
    - name: OIDC_CLIENT_ID
      value: 45104d6a-f5bc-4e8c-b352-4bbfc9381f25
    - name: TOKEN_COOKIE_NAME
      value: selvbetjening-idtoken
    - name: GCS_BUCKET_NAME
      value: start-samtale-prod
    - name: CONTEXT_PATH
      value: /arbeid/start-samtale
    - name: JSON_CONFIG
      value: >
        {
          "proxies": [
            { "from": "/veilarbvedtakinfo", "to": "http://pto-proxy/proxy/veilarbvedtakinfo" },
            { "from": "/veilarboppfolging", "to": "http://pto-proxy/proxy/veilarboppfolging" },
            { "from": "/veilarbdialog", "to": "http://pto-proxy/proxy/veilarbdialog" }
          ],
          "redirects": [
            {
              "from": "/dittnav",
              "to": "{{DITTNAV_URL}}"
            },
            {
              "from": "/arbeidsrettet-dialog",
              "to": "{{ARBEIDSRETTET_DIALOG_URL}}",
              "preserveContextPath": "true"
            }
          ]
        }
