apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: start-samtale
  namespace: pto
  labels:
    team: pto
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.04.14_11.14-66f2c0b9e68b
  port: 8080
  liveness:
    path: /internal/alive
    initialDelay: 20
  readiness:
    path: /internal/ready
    initialDelay: 20
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  ingresses:
    - https://www.nav.no/arbeid/start-samtale
  resources:
    limits:
      cpu: "3"
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 512Mi
  idporten:
    enabled: true
    sidecar:
      enabled: true
      autoLogin: true
  tokenx:
    enabled: true
  gcp:
    buckets:
      - name: start-samtale-prod
  accessPolicy:
    outbound:
      external:
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbdialog.prod-fss-pub.nais.io
        - host: veilarbvedtakinfo.prod-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "gcs": {
            "bucketName": "start-samtale-prod"
          },
          "auth": {
            "loginProvider": "ID_PORTEN"
          },
          "cors": { "origin": "*.nav.no" },
          "header": {
            "csp": {
              "defaultSrc":["'self'", "*.nav.no"],
              "scriptSrc":["'self'", "*.nav.no","*.psplugin.com","*.hotjar.com","*.taskanalytics.com","'unsafe-inline'","'unsafe-eval'", "blob:", "*.boost.ai"],
              "styleSrc":["*.nav.no","*.psplugin.com","'unsafe-inline'"],
              "fontSrc":["*.psplugin.com","*.hotjar.com","cdn.nav.no","data:"],
              "imgSrc":["*.nav.no","*.psplugin.com","*.vimeocdn.com","*.hotjar.com","www.vergic.com"],
              "frameSrc":["*.hotjar.com","player.vimeo.com","video.qbrick.com"],
              "connectSrc":["*.nav.no","*.boost.ai","*.psplugin.com","*.hotjar.com","*.hotjar.io","*.taskanalytics.com"]
            }
          },
          "contextPath": "/arbeid/start-samtale",
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "proxies": [  
            { "fromPath": "/veilarbvedtakinfo", "toUrl": "https://veilarbvedtakinfo.prod-fss-pub.nais.io/veilarbvedtakinfo", "toApp": { "name": "veilarbvedtakinfo", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarboppfolging", "toUrl": "https://veilarboppfolging.prod-fss-pub.nais.io/veilarboppfolging", "toApp": { "name": "veilarboppfolging", "namespace": "pto", "cluster": "prod-fss" } },
            { "fromPath": "/veilarbdialog", "toUrl": "https://veilarbdialog.prod-fss-pub.nais.io/veilarbdialog", "toApp": { "name": "veilarbdialog", "namespace": "pto", "cluster": "prod-fss" } }
          ]
        }
