name: Deploy feature branch
on:
  workflow_dispatch:

concurrency:
  group: deploy-feature-branch
  cancel-in-progress: true

jobs:
  deploy-dev:
    name: Deploy application to dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build application
        run: npm run build-dev
      - name: Gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCS_SA_KEY_DEV }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Upload files to GCS
        run: gsutil -m rsync -r dist gs://start-samtale-dev