name: pto frontend container

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/pto-frontend-container.yml'
      - 'nais-dev.yaml'
      - 'nais-prod.yaml'
  workflow_dispatch:

concurrency:
  group: pto_frontend_container
  cancel-in-progress: true

env:
  APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: deploy dev
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
      - name: deploy prod
        if: github.ref == 'refs/heads/main'
        uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
